apiVersion: v1
kind: ServiceAccount
metadata:
  name: devopsblog-s3
  namespace: devopsblog-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648835056994:role/devopsblog-prod-s3-reader
