apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-sysconfig
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/valentindodovu51/devopsblog-gitops.git'
    targetRevision: master
    path: argocd-sysconfig
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false