apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsblog
  namespace: devopsblog-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devopsblog
      app.kubernetes.io/instance: devopsblog-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devopsblog
        app.kubernetes.io/instance: devopsblog-dev
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: devopsblog
          image: 648835056994.dkr.ecr.eu-central-1.amazonaws.com/devops-blog:dev-fix-posts-1
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 21
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi