apiVersion: v1
kind: ServiceAccount
metadata:
  name: devopsblog-s3
  namespace: devopsblog-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::648835056994:role/devopsblog-dev-s3-reader
