name: Autobot enables automatic PR merge

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-24.04
    steps:


      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}



      - name: Get GitHub App secret from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ghapp, github/devopsblog/github-app
          name-transformation: lowercase
          parse-json-secrets: true



      - name: Create GitHub App token
        id: apptoken
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ env.ghapp_app_id }}
          private-key: ${{ env.ghapp_private_key_pem }}
          owner: valentindodovu51
          repositories: devopsblog-gitops



      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ steps.apptoken.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --merge "$PR_URL"